"""Step 1b: turn ``src/pyaisc360/data/spec_index.json`` into the build roadmap.

The MODULE_MAP below is the single source of truth for "which chapter becomes
which file, in which wave, and what is deliberately out of scope".  ``pytest
tests/test_coverage.py`` reads the same map, so the roadmap and the library
cannot silently drift apart.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

# chapter -> (module, wave, scope note)
#   wave 0 = foundations, 1 = member strength (priority per the brief),
#   2 = interaction + stability, 3 = connections, 4 = composite/specialist,
#   X = non-computational, not implemented as code.
MODULE_MAP: dict[str, tuple[str, str, str]] = {
    "B": ("chapter_b.py", "0", "B3 design basis (phi/Omega), B4 width-to-thickness classification (Tables B4.1a/b), net/gross area"),
    "D": ("chapter_d.py", "1", "Tension: yielding, rupture, shear lag U (Table D3.1), pin-connected, eyebars"),
    "E": ("chapter_e.py", "1", "Compression: FB, TB, FTB, single angles, built-up, slender (effective area)"),
    "F": ("chapter_f.py", "1", "Flexure: F2-F13, all shapes, all limit states (Y, LTB, FLB, WLB, TFY, LLB)"),
    "G": ("chapter_g.py", "1", "Shear: I-shapes with/without tension field action, angles, tees, HSS, weak axis"),
    "C": ("chapter_c.py", "2", "Direct analysis method: stiffness reduction tau_b, notional loads, Lc=L"),
    "H": ("chapter_h.py", "2", "Combined forces: H1 interaction, H2 unsymmetric, H3 torsion, H4 flange rupture"),
    "J": ("chapter_j.py", "3", "Connections: welds, bolts, block shear, bearing, column bases, concentrated forces"),
    "K": ("chapter_k.py", "4", "HSS connections: concentrated forces, truss and moment connections, welds to HSS"),
    "I": ("chapter_i.py", "4", "Composite: encased/filled columns, composite beams, shear studs, load transfer"),
    "L": ("chapter_l.py", "4", "Serviceability: deflection/drift/vibration advisory limits only (no mandatory equations)"),
    "A": ("-", "X", "Scope, referenced standards, materials -> folded into materials.py"),
    "M": ("-", "X", "Fabrication and erection -- not a calculation chapter"),
    "N": ("-", "X", "Quality control / quality assurance -- not a calculation chapter"),
    "A1": ("appendix_1.py", "4", "Design by advanced analysis (direct modeling of imperfections/inelasticity)"),
    "A2": ("appendix_2.py", "4", "Design for ponding"),
    "A3": ("appendix_3.py", "4", "Fatigue: stress categories, threshold and allowable stress ranges"),
    "A4": ("appendix_4.py", "4", "Structural design for fire conditions (elevated-temperature properties)"),
    "A5": ("-", "X", "Evaluation of existing structures -- procedural"),
    "A6": ("appendix_6.py", "2", "Member stability bracing: panel/point bracing strength and stiffness"),
    "A7": ("appendix_7.py", "2", "Effective length method and first-order analysis method"),
    "A8": ("appendix_8.py", "2", "Approximate second-order analysis: B1 / B2 amplifiers"),
}

WAVE_TITLE = {
    "0": "Wave 0 - Foundations",
    "1": "Wave 1 - Member strength (priority)",
    "2": "Wave 2 - Stability and combined forces",
    "3": "Wave 3 - Connections",
    "4": "Wave 4 - Specialist chapters",
    "X": "Not implemented as code (non-computational)",
}


def build(index: dict) -> str:
    eqs = index["equations"]
    tables = index["tables"]
    # Keyed by chapter too: the Specification labels both Chapter A's sections
    # and the appendices "A1".."A8", so a bare label is ambiguous.
    sections = {f"{s['chapter']}:{s['label']}": s for s in index["sections"]}
    per_chapter = index["counts"]["per_chapter"]
    per_section = index["counts"]["per_section"]

    out: list[str] = []
    w = out.append

    w("# pyaisc360 - Build Roadmap (Step 1 output)")
    w("")
    w("Generated by `tools/gen_roadmap.py` from `src/pyaisc360/data/spec_index.json`.")
    w(f"Source: **{index['spec']}** (`{index['source']}`), "
      f"body lines {index['body_lines'][0]}-{index['body_lines'][1]}.")
    w("")
    w(f"**{index['counts']['equations']} numbered equations**, "
      f"**{index['counts']['tables']} tables**, "
      f"**{index['counts']['sections']} sections** catalogued.")
    w("")
    w("Every equation below carries its source line and *Specification* page (`16.1-nn`),")
    w("which the implementing function repeats in its docstring. `tests/test_coverage.py`")
    w("fails if a catalogued equation has neither an implementation nor a listed waiver.")
    w("")

    # ---- wave table -----------------------------------------------------
    w("## Chapter -> module map")
    w("")
    for wave in ["0", "1", "2", "3", "4", "X"]:
        rows = [(ch, v) for ch, v in MODULE_MAP.items() if v[1] == wave]
        if not rows:
            continue
        w(f"### {WAVE_TITLE[wave]}")
        w("")
        w("| Chapter | Module | Eqs | Tables | Scope |")
        w("|---|---|---:|---:|---|")
        for ch, (mod, _, note) in rows:
            n_eq = per_chapter.get(ch, 0)
            n_tab = sum(1 for t in tables if t["chapter"] == ch)
            name = f"Appendix {ch[1:]}" if ch.startswith("A") and len(ch) > 1 else f"Chapter {ch}"
            w(f"| {name} | `{mod}` | {n_eq} | {n_tab} | {note} |")
        w("")

    # ---- per-section detail --------------------------------------------
    w("## Section inventory")
    w("")
    # An equation's own ``chapter`` field disambiguates Chapter A's sections
    # (A1..A4) from the appendices, which the Specification also labels A1..A8.
    chapter_of = {e["section"]: e["chapter"] for e in eqs}
    current_chapter = None
    for lbl in sorted(per_section, key=lambda s: (s[0], int("".join(c for c in s[1:] if c.isdigit()) or 0))):
        ch = chapter_of[lbl]
        if ch != current_chapter:
            current_chapter = ch
            mod = MODULE_MAP.get(ch, ("?", "?", ""))[0]
            name = f"Appendix {ch[1:]}" if len(ch) > 1 else f"Chapter {ch}"
            w("")
            w(f"### {name} -> `{mod}`")
            w("")
            w("| Section | Title | Page | Equations |")
            w("|---|---|---|---|")
        sec = sections.get(f"{ch}:{lbl}")
        # Appendix subsections are numbered "6.2." style and are not captured as
        # top-level headings, so fall back to the appendix scope note.
        title = sec["title"] if sec else MODULE_MAP.get(ch, ("", "", "-"))[2]
        page = f"16.1-{sec['page']}" if sec and sec["page"] else "-"
        labels = ", ".join(e["label"] for e in eqs if e["section"] == lbl)
        w(f"| **{lbl}** | {title} | {page} | {labels} |")
    w("")

    # ---- tables ---------------------------------------------------------
    w("## Lookup tables to encode as data")
    w("")
    w("| Table | Chapter | Page | Line | Planned home |")
    w("|---|---|---|---|---|")
    table_home = {
        "B4.1a": "`data/tables/b4_1a.json` - axial compression element slenderness",
        "B4.1b": "`data/tables/b4_1b.json` - flexural element slenderness",
        "D3.1": "`data/tables/d3_1.json` - shear lag factors U",
        "E7.1": "`chapter_e.py` - effective width imperfection factors c1/c2",
        "J2.1": "`data/tables/j2_1.json` - effective throat of PJP groove welds",
        "J2.2": "`data/tables/j2_2.json` - effective weld sizes of flare groove welds",
        "J2.3": "`data/tables/j2_3.json` - minimum effective throat, PJP",
        "J2.4": "`data/tables/j2_4.json` - minimum fillet weld size",
        "J2.5": "`data/tables/j2_5.json` - available strength of welded joints",
        "J3.1": "`data/tables/j3_1.json` - minimum bolt pretension (+ J3.1M metric)",
        "J3.2": "`data/tables/j3_2.json` - nominal Fnt / Fnv of fasteners",
        "J3.3": "`data/tables/j3_3.json` - nominal hole dimensions (+ J3.3M)",
        "J3.4": "`data/tables/j3_4.json` - minimum edge distance (+ J3.4M)",
        "J3.5": "`data/tables/j3_5.json` - hole-type slip factors (+ J3.5M)",
    }
    for t in tables:
        home = table_home.get(t["label"], "deferred (wave 4)")
        w(f"| {t['label']} | {t['chapter']} | 16.1-{t['page']} | {t['line']} | {home} |")
    w("")

    w("## Known gaps in the source text")
    w("")
    w("1. **Section property data is not in the Specification.** The AISC *Shapes Database*")
    w("   (v15.0) is a separate publication. `pyaisc360.sections` is therefore data-driven:")
    w("   it ships a small verified seed catalog and loads the full database from a")
    w("   user-supplied CSV via `ShapeDatabase.from_csv()`.")
    w("2. **The text dump breaks subscripts onto their own lines** (`P =F A` / `n  cr g`) and")
    w("   mangles Greek letters. Equations are therefore transcribed by hand and verified")
    w("   against AISC *Design Examples V16.0*, not machine-translated from the dump.")
    w("3. **Chapters M and N and Appendix 5 are procedural** (fabrication, QA, evaluation of")
    w("   existing structures) and contain no design equations to implement.")
    w("")
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--index",
        default=Path("src/pyaisc360/data/spec_index.json"),
        type=Path,
    )
    ap.add_argument("--out", default=Path("ROADMAP.md"), type=Path)
    args = ap.parse_args()

    index = json.loads(args.index.read_text(encoding="utf-8"))
    args.out.write_text(build(index), encoding="utf-8")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
